<a href="https://colab.research.google.com/github/Surya-dev-lang/datascience/blob/master/mnist%20digit%20recognition%20using%20NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import keras
from keras.datasets import mnist
from keras.layers import Dense
from keras.models import Sequential

In [0]:
batch_size = 128
num_classes = 10
epochs = 20

In [0]:
def get_data():
  (x_train,y_train), (x_test, y_test) = mnist.load_data()
  x_train = x_train.reshape(60000, 784)
  x_test = x_test.reshape(10000, 784)
  x_train = x_train.astype('float32')
  x_test = x_test.astype('float32')
  x_train /= 255
  x_test /= 255
  print(x_train.shape, 'train samples')
  print(x_test.shape, 'train samples')

  y_train = keras.utils.to_categorical(y_train, num_classes)
  y_test =  keras.utils.to_categorical(y_test, num_classes)

  return (x_train, y_train), (x_test, y_test)

In [22]:
get_data()

(60000, 784) train samples
(10000, 784) train samples


((array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
  array([[0., 0., 0., ..., 0., 0., 0.],
         [1., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)),
 (array([[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]], dtype=float32),
  array([[0., 0., 0., ..., 1., 0., 0.],
         [0., 0., 1., ..., 0., 0., 0.],
         [0., 1., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0.

In [23]:
model = Sequential()
model.add(Dense(512, activation='relu', input_shape=(784,)))
model.add(Dense(512, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [24]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 512)               262656    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                5130      
Total params: 669,706
Trainable params: 669,706
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.compile(loss='categorical_crossentropy',
              optimizer = 'adam',
              metrics = ['accuracy'])

In [26]:
(x_train, y_train), (x_test, y_test)= get_data()

(60000, 784) train samples
(10000, 784) train samples


In [27]:
history = model.fit(x_train, y_train,
                    batch_size=batch_size,
                    epochs=epochs,
                    verbose=1,
                    validation_data=(x_test, y_test))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Train on 60000 samples, validate on 10000 samples
Epoch 1/20
60000/60000 [==============================] - 11s 179us/step - loss: 0.2206 - acc: 0.9350 - val_loss: 0.0938 - val_acc: 0.9714
Epoch 2/20
60000/60000 [==============================] - 10s 165us/step - loss: 0.0803 - acc: 0.9754 - val_loss: 0.0735 - val_acc: 0.9767
Epoch 3/20
60000/60000 [==============================] - 10s 165us/step - loss: 0.0507 - acc: 0.9837 - val_loss: 0.0664 - val_acc: 0.9793
Epoch 4/20
60000/60000 [==============================] - 10s 161us/step - loss: 0.0378 - acc: 0.9869 - val_loss: 0.0666 - val_acc: 0.9811
Epoch 5/20
60000/60000 [==============================] - 10s 161us/step - loss: 0.0266 - acc: 0.9914 - val_loss: 0.0810 - val_acc: 0.9792
Epoch 6/20
60000/60000 [==============================] - 10s 168us/step - loss: 0.0210 - acc: 0.9931 - val_loss: 0.0611 - val_acc: 0.9826
Epoch 7/20
60000/6000

In [32]:
score= model.evaluate(x_test, y_test, verbose=0)
print('Test Loss:',score[0])
print('Test Accuracy:', score[1])

Test Loss: 0.10564764755337423
Test Accuracy: 0.9803
